dvhd/Models/banner.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dvhd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class banner
    {
        public int id { get; set; }
        public string images { get; set; }
        public Nullable<int> no { get; set; }
        public string link { get; set; }
        public Nullable<int> type { get; set; }
    }
}

dvhd/Controllers/BannerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dvhd.Models;

namespace dvhd.Controllers
{
    public class BannerController : Controller
    {
        private dvhdEntities db = new dvhdEntities();

        //
        // GET: /Banner/

        public ActionResult Index()
        {
            return View(db.banners.OrderBy(o=>o.no).ThenByDescending(o=>o.id).ToList());
        }

        //
        // GET: /Banner/Details/5

        public ActionResult Details(int id = 0)
        {
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }
        [HttpPost]
        [AcceptVerbs(HttpVerbs.Post)]
        public string UploadImageProcess(HttpPostedFileBase file, string filename)
        {
            string physicalPath = HttpContext.Server.MapPath("../" + Config.SlideImagePath + "\\");
            string nameFile = String.Format("{0}.jpg", filename);
            int countFile = Request.Files.Count;
            string fullPath = physicalPath + System.IO.Path.GetFileName(nameFile);
            for (int i = 0; i < countFile; i++)
            {
                if (System.IO.File.Exists(fullPath))
                {
                    System.IO.File.Delete(fullPath);
                }
                Request.Files[i].SaveAs(fullPath);
                break;
            }
            //string ok = resizeImage(Config.imgWidthBigSlide, Config.imgHeightBigSlide, fullPath, Config.SlideImagePath + "/" + nameFile);
            return Config.SlideImagePath + "/" + nameFile;
        }
        //
        // GET: /Banner/Create

        public ActionResult Create()
        {
            ViewBag.filename = Guid.NewGuid().ToString();
            return View();
        }

        //
        // POST: /Banner/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(banner banner)
        {
            if (ModelState.IsValid)
            {
                db.banners.Add(banner);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(banner);
        }

        //
        // GET: /Banner/Edit/5

        public ActionResult Edit(int id = 0)
        {
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            ViewBag.filename = Guid.NewGuid().ToString();
            return View(banner);
        }

        //
        // POST: /Banner/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(banner banner)
        {
            if (ModelState.IsValid)
            {
                db.Entry(banner).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(banner);
        }

        //
        // GET: /Banner/Delete/5

        public ActionResult Delete(int id = 0)
        {
            banner banner = db.banners.Find(id);
            if (banner == null)
            {
                return HttpNotFound();
            }
            return View(banner);
        }

        //
        // POST: /Banner/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            banner banner = db.banners.Find(id);
            db.banners.Remove(banner);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

dvhd/Views/Banner/Create.cshtml
@model dvhd.Models.banner

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thêm mới banner</h2>
@using (Html.BeginForm("Create", "Banner", FormMethod.Post, new { id = "EditForm" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>                       
        <div class="col-md-6">
              <div class="form-group">
                <label for="room" style="width:auto;display:block;">Upload ảnh banner trang chủ (gợi ý kích cỡ 848x300)</label>
                <input name="imageFile" type="file" id="imageFile" value="" multiple="multiple" class="form-control" runat="server" onchange="uploadProcess();"/>                                
                <div id="progressbar" class="progressbar">
                    <div id="progresslabel" class="progressbarlabel"></div>
                 </div>  
              </div>
         </div> 
         <div class="col-md-6">
              <div class="form-group">
                <label for="room" style="width:auto;display:block;">Ảnh nền</label>
                <input name="images" type="hidden" id="images" value="" class="form-control" />                  
                  <div id="imageShow" style="width:600px;height:200px;"></div>
              </div>
         </div>         
         <div class="col-md-6" style="display:none;">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">link đến</label>
                 <input name="link" type="text" id="link" value="" class="form-control" placeholder="đường dẫn khi click vào text"/>
              </div>
        </div>
        <div class="col-md-6">
              <div class="form-group">
                <label for="room" style="width:auto;display:block;">Vị trí xuất hiện</label>                
                <select class="form-control" name="no" id="no">
                    <option selected="selected" disabled="disabled" value="">Chọn thứ tự xuất hiện</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                </select>
                <input type="hidden" id="type" name="type" value="0">
              </div>
        </div>               
    </fieldset>
}
<p>
    <button type="button" class="btn btn-info" onclick="checkField();">Thêm mới</button>
</p>
<div>
    @Html.ActionLink("Danh sách", "Index")
</div>
<div id="loadingImage" name="loadingImage" style="z-index:1000;position:fixed;left:40%;top:30%;width:32px;height:32px;display:none;">
    <img src="/Images/loading.gif">
</div>
<script>

    //Image upload
    function uploadProcess() {
        var formdata = new FormData(); //FormData object
        var fileInput = document.getElementById('imageFile');
        for (i = 0; i < fileInput.files.length; i++) {
            //Appending each file to FormData object
            formdata.append(fileInput.files[i].name, fileInput.files[i]);
            break;
        }
        formdata.append("filename", "@ViewBag.filename");
        showLoadingImage();
        var xhr = new XMLHttpRequest();
        xhr.upload.addEventListener("progress", function (evt) {
            if (evt.lengthComputable) {
                var progress = Math.round(evt.loaded * 100 / evt.total);
                $("#progressbar").progressbar("value", progress);
            }
        }, false);
        xhr.open('POST', '/Banner/UploadImageProcess');
        xhr.send(formdata);
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                $('#imageShow').html("<img src=\"" + xhr.responseText + "\" width=600 height=200>");
                $('#images').val(xhr.responseText);
                hideLoadingImage();
            }
        }
        return false;
    }
    
    $("#progressbar").progressbar({
        max: 100,
        change: function (evt, ui) {
            $("#progresslabel").text($("#progressbar").progressbar("value") + "%");
        },
        complete: function (evt, ui) {
            $("#progresslabel").text("File upload successful!");
        }
    });
  
    function checkField() {

        if (document.getElementById("images").value == "") {
            alert("upload ảnh nền!");
            return false;
        }
        if (document.getElementById("no").value == "") {
            alert("Nhập vị trí xuất hiện!");
            document.getElementById("no").focus();
            return false;
        }
        document.getElementById("EditForm").submit();
    }

    evt.preventDefault();
</script>

dvhd/Views/Banner/Delete.cshtml
@model dvhd.Models.banner

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Xóa banner</h2>

<h3>Bạn có chắc chắn xóa ảnh này?<img src="@Model.images" width="600px" height="300px"></h3>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Xóa" /> |
        @Html.ActionLink("Quay lại danh sách", "Index")
    </p>
}

dvhd/Views/Banner/Details.cshtml
@model dvhd.Models.banner

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>banner</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.images)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.images)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.no)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.no)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.link)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.link)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.type)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.type)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

dvhd/Views/Banner/Edit.cshtml
@model dvhd.Models.banner

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Cập nhật banner</h2>
@using (Html.BeginForm("Edit", "Banner", FormMethod.Post, new { id = "EditForm" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>                       
        <div class="col-md-6">
              <div class="form-group">
                <label for="room" style="width:auto;display:block;">Upload ảnh banner trang chủ (gợi ý kích cỡ 848x300)</label>
                <input name="imageFile" type="file" id="imageFile" value="" multiple="multiple" class="form-control" runat="server" onchange="uploadProcess();"/>                                
                <div id="progressbar" class="progressbar">
                    <div id="progresslabel" class="progressbarlabel"></div>
                 </div>  
              </div>
         </div> 
         <div class="col-md-6">
              <div class="form-group">
                <label for="room" style="width:auto;display:block;">Ảnh nền</label>
                <input name="images" type="hidden" id="images" value="@Model.images" class="form-control" />                  
                  <div id="imageShow" style="width:600px;height:200px;"><img src="@Model.images" width="600px" height="300px"></div>
              </div>
         </div>         
         <div class="col-md-6" style="display:none;">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">link đến</label>
                 <input name="link" type="text" id="link" value="" class="form-control" placeholder="đường dẫn khi click vào text"/>
              </div>
        </div>
        <div class="col-md-6">
              <div class="form-group">
                <label for="room" style="width:auto;display:block;">Vị trí xuất hiện</label>                
                <select class="form-control" name="no" id="no">
                    <option selected="selected" disabled="disabled" value="">Chọn thứ tự xuất hiện</option>
                    <option value="1">1</option>
                    <option value="2">2</option>
                    <option value="3">3</option>
                    <option value="4">4</option>
                    <option value="5">5</option>
                    <option value="6">6</option>
                    <option value="7">7</option>
                    <option value="8">8</option>
                    <option value="9">9</option>
                    <option value="10">10</option>
                    <option value="11">11</option>
                </select>
                <script>document.getElementById("no").value=@Model.no;</script>
                <input type="hidden" id="type" name="type" value="0">
              </div>
        </div>               
    </fieldset>
}
<p>
    <button type="button" class="btn btn-info" onclick="checkField();">Cập nhật</button>
</p>
<div>
    @Html.ActionLink("Danh sách", "Index")
</div>
<div id="loadingImage" name="loadingImage" style="z-index:1000;position:fixed;left:40%;top:30%;width:32px;height:32px;display:none;">
    <img src="/Images/loading.gif">
</div>
<script>

    //Image upload
    function uploadProcess() {
        var formdata = new FormData(); //FormData object
        var fileInput = document.getElementById('imageFile');
        for (i = 0; i < fileInput.files.length; i++) {
            //Appending each file to FormData object
            formdata.append(fileInput.files[i].name, fileInput.files[i]);
            break;
        }
        formdata.append("filename", "@ViewBag.filename");
        showLoadingImage();
        var xhr = new XMLHttpRequest();
        xhr.upload.addEventListener("progress", function (evt) {
            if (evt.lengthComputable) {
                var progress = Math.round(evt.loaded * 100 / evt.total);
                $("#progressbar").progressbar("value", progress);
            }
        }, false);
        xhr.open('POST', '/Banner/UploadImageProcess');
        xhr.send(formdata);
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                $('#imageShow').html("<img src=\"" + xhr.responseText + "\" width=600 height=200>");
                $('#images').val(xhr.responseText);
                hideLoadingImage();
            }
        }
        return false;
    }

    $("#progressbar").progressbar({
        max: 100,
        change: function (evt, ui) {
            $("#progresslabel").text($("#progressbar").progressbar("value") + "%");
        },
        complete: function (evt, ui) {
            $("#progresslabel").text("File upload successful!");
        }
    });

    function checkField() {

        if (document.getElementById("images").value == "") {
            alert("upload ảnh nền!");
            return false;
        }
        if (document.getElementById("no").value == "") {
            alert("Nhập vị trí xuất hiện!");
            document.getElementById("no").focus();
            return false;
        }
        document.getElementById("EditForm").submit();
    }

    evt.preventDefault();
</script>

dvhd/Views/Banner/Index.cshtml
@model IEnumerable<dvhd.Models.banner>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2 style="margin-left:10px;">Danh sách banner trên trang chủ</h2>

<p style="margin-left:10px;">
    @Html.ActionLink("Thêm mới", "Create")
</p>
<table style="margin-left:10px;border: 1px solid #36813c;border-collapse : collapse;width:100%;" >
    <tr>
        <th style="border: 1px solid #36813c; padding: 2px !important;">
            Ảnh
        </th>
        <th style="border: 1px solid #36813c; padding: 2px !important;">
            Vị trí xuất hiện
        </th>        
        <th style="border: 1px solid #36813c; padding: 2px !important;"></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td style="border: 1px solid #36813c; padding: 2px !important;">
            <img src="@item.images" width="600px" height="300px">
        </td>
        <td align="center" style="border: 1px solid #36813c; padding: 2px !important;">
            @item.no
        </td>       
        <td style="border: 1px solid #36813c; padding: 2px !important;">
            @Html.ActionLink("Sửa", "Edit", new { id=item.id }) |            
            @Html.ActionLink("Xóa", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>