dvhd/Models/user.cs
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dvhd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string name { get; set; }
        public string pass { get; set; }
        public string groups { get; set; }
        public string permission { get; set; }
    }
}

dvhd/Controllers/usersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using dvhd.Models;
using PagedList;
using System.Security.Cryptography;
namespace dvhd.Controllers
{
    public class usersController : Controller
    {
        private dvhdEntities db = new dvhdEntities();

        //
        // GET: /users/

        public ActionResult Index(int? page)
        {
            if (Config.getCookie("logged") == "") return RedirectToAction("Login", "Home");
            if (!Config.checkPermission(Config.getCookie("logged"), "US0")) return RedirectToAction("Permission", "Home");

            var p = (from q in db.users select q).OrderByDescending(o => o.id).Take(1000);
            int pageSize = Config.PageSize;
            int pageNumber = (page ?? 1);
            ViewBag.page = page;
            return View(p.ToPagedList(pageNumber, pageSize));
        }

        //
        // GET: /users/Details/5

        public ActionResult Details(int id = 0)
        {
            user user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // GET: /users/Create

        public ActionResult Create()
        {
            if (Config.getCookie("logged") == "") return RedirectToAction("Login", "Home");
            if (!Config.checkPermission(Config.getCookie("logged"), "US1")) return RedirectToAction("Permission", "Home");
            return View();
        }

        //
        // POST: /users/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(user user)
        {
            if (ModelState.IsValid)
            {
                string pass = user.pass;
                MD5 md5Hash = MD5.Create();
                string hash = Config.GetMd5Hash(md5Hash, pass);
                user.pass = hash;
                db.users.Add(user);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(user);
        }
        public ActionResult changePass() {
            ViewBag.id = Config.getCookie("userid");
            ViewBag.username = Config.getCookie("username");
            return View();
        }
        public string updatePass(int id,string oldpass,string pass) {
            try
            {
                MD5 md5Hash = MD5.Create();
                string hash = Config.GetMd5Hash(md5Hash, pass);
                oldpass = Config.GetMd5Hash(md5Hash, oldpass);
                var p = db.users.Where(o => o.id == id).Where(o => o.pass.Contains(oldpass)).FirstOrDefault().name;

                if (p != null && p != "")
                {
                    db.Database.ExecuteSqlCommand("update users set pass=N'" + hash + "' where id=" + id);
                    return "1";
                }
                else return "0";
                
            }
            catch (Exception ex) {
                return "0";
            }
        }
        public string updatePermission(int id, string permission)
        {
            try
            {
                db.Database.ExecuteSqlCommand("update users set permission=N'" + permission + "' where id=" + id);
                return "1";
            }
            catch (Exception ex) {
                return "0";
            }
        }
        [HttpPost]
        public string Login(string name, string pass)
        {
            try
            {
                MD5 md5Hash = MD5.Create();
                pass = Config.GetMd5Hash(md5Hash, pass);
                var p = (from q in db.users where q.name.Contains(name) && q.pass.Contains(pass) select q).FirstOrDefault();
                if (p != null && p.name != "")
                {
                    //Ghi ra cookie
                    Config.setCookie("logged", p.permission);
                    Config.setCookie("username", p.name);
                    Config.setCookie("userid", p.id.ToString());
                    return "1";
                }
                else
                {
                    return "0";
                }
            }
            catch (Exception ex) {
                return "0";
            }
            //return "0";
        }
        //
        // GET: /users/Edit/5

        public ActionResult Edit(int id = 0)
        {
            if (Config.getCookie("logged") == "") return RedirectToAction("Login", "Home");
            if (!Config.checkPermission(Config.getCookie("logged"), "US2")) return RedirectToAction("Permission", "Home");
            user user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = id;
            return View(user);
        }

        //
        // POST: /users/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(user user)
        {
            if (ModelState.IsValid)
            {
                string pass = user.pass;
                MD5 md5Hash = MD5.Create();
                string hash = Config.GetMd5Hash(md5Hash, pass);
                user.pass = hash;
                db.Entry(user).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(user);
        }

        //
        // GET: /users/Delete/5

        public ActionResult Delete(int id = 0)
        {
            if (Config.getCookie("logged") == "") return RedirectToAction("Login", "Home");
            if (!Config.checkPermission(Config.getCookie("logged"), "US3")) return RedirectToAction("Permission", "Home");
            user user = db.users.Find(id);
            if (user == null)
            {
                return HttpNotFound();
            }
            return View(user);
        }

        //
        // POST: /users/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            user user = db.users.Find(id);
            db.users.Remove(user);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

dvhd/Views/users/Create.cshtml
@model dvhd.Models.user
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Thêm user và phân quyền</h2>
@using (Html.BeginForm("Create", "users", FormMethod.Post, new { id = "EditForm" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)
    <fieldset>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">User name * </label>
                 <input name="name" type="text" tabindex="1" id="name" value="" class="form-control" placeholder="Nhập user name"/>               
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">password * </label>
                 <input name="pass" type="password" tabindex="1" id="pass" value="" class="form-control" placeholder="Nhập password"/>               
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">Thuộc đơn vị * </label>
                 <select id="groups" class="form-control" name="groups" tabindex="33" onchange="changePermission();">                   
                    <option value="Tổng cục môi trường">Tổng cục môi trường</option>
                    <option value="Cảnh sát môi trường" selected>Cảnh sát môi trường</option>
                    <option value="Hải quan">Hải quan</option>
                    <option value="Kiểm lâm">Kiểm lâm</option>
                    <option value="Quản lý thị trường">Quản lý thị trường</option>
                    <option value="Viện kiểm sát">Viện kiểm sát</option>
                    <option value="Tòa án">Tòa án</option>
                    <option value="Cơ quan điều tra">Cơ quan điều tra</option>
                    <option value="Nhập dữ liệu">Nhập dữ liệu</option>
                    <option value="Admin hệ thống">Admin hệ thống</option>
                </select>              
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">PHÂN QUYỀN CHO USER</label>
                 <input type="checkbox" id="ALL" onclick="checkAll(this, 'ALL');">TẤT CẢ   
                 <input type="hidden" value="" id="permission" name="permission">          
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="HS" onclick="checkHS();">Quyền truy cập Quản lý hồ sơ vi phạm</label>
                 <input type="checkbox" id="HS0" onclick="checkPermission(this, 'HS0');">Xem danh sách 
                 <input type="checkbox" id="HS1" onclick="checkPermission(this, 'HS1');">Tạo mới hồ sơ
                 <input type="checkbox" id="HS2" onclick="checkPermission(this, 'HS2');">Xem và in hồ sơ 
                 <input type="checkbox" id="HS3" onclick="checkPermission(this, 'HS3');">Sửa hồ sơ 
                 <input type="checkbox" id="HS4" onclick="checkPermission(this, 'HS4');">Xóa hồ sơ             
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="BC_1_5" onclick="checkBC(1, 5);">Quyền truy cập Tra cứu hồ sơ</label>
                 <input type="checkbox" id="BC1" onclick="checkPermission(this, 'BC1');">Tra cứu theo loài bị vi phạm
                 <input type="checkbox" id="BC2" onclick="checkPermission(this, 'BC2');">Tra cứu theo địa bàn vi phạm
                 <input type="checkbox" id="BC3" onclick="checkPermission(this, 'BC3');">Tra cứu theo đối tượng vi phạm
                 <input type="checkbox" id="BC4" onclick="checkPermission(this, 'BC4');">Tra cứu theo đơn vị bắt giữ
                 <input type="checkbox" id="BC5" onclick="checkPermission(this, 'BC5');">Tra cứu theo đơn vị xử lý
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="BC_6_11" onclick="checkBC(6, 11);">Quyền truy cập xem các báo cáo</label>
                 <input type="checkbox" id="BC6" onclick="checkPermission(this, 'BC6');">Xem báo cáo theo hình thức vi phạm(hành chính, hình sự)
                 <input type="checkbox" id="BC7" onclick="checkPermission(this, 'BC7');">Xem báo cáo theo hành vi vi phạm(buôn bán, vận chuyển, nuôi nhốt...)
                 <input type="checkbox" id="BC8" onclick="checkPermission(this, 'BC8');">Xem báo cáo số vụ xử lý hành chính
                 <input type="checkbox" id="BC9" onclick="checkPermission(this, 'BC9');">Xem báo cáo số vụ xử lý hình sự
                 <input type="checkbox" id="BC10" onclick="checkPermission(this, 'BC10');">Xem báo cáo số vụ không xử lý 
                 <input type="checkbox" id="BC11" onclick="checkPermission(this, 'BC11');">Xem báo cáo tổng hợp   
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="US" onclick="checkUS();">Quyền truy cập quản lý user đăng nhập</label>
                 <input type="checkbox" id="US0" onclick="checkPermission(this, 'US0');">Xem danh sách user đăng nhập
                 <input type="checkbox" id="US1" onclick="checkPermission(this, 'US1');">Tạo user đăng nhập
                 <input type="checkbox" id="US2" onclick="checkPermission(this, 'US2');">Sửa user đăng nhập 
                 <input type="checkbox" id="US3" onclick="checkPermission(this, 'US3');">Xóa user đăng nhập    
              </div>
        </div>
         <p>
            <input type="button" value="Thêm mới" onclick="checkField();" />
        </p>
    </fieldset>
}    
<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>
<script>
    
    function checkField() {
        //alert(document.getElementById("permission").value);
        //return;
        if (document.getElementById("name").value == "") {
            alert("Nhập user name");
            document.getElementById("name").focus();
            return;
        }
        if (document.getElementById("pass").value == "") {
            alert("Nhập password");
            document.getElementById("pass").focus();
            return;
        }
        if (document.getElementById("permission").value == "") {
            alert("Bạn chưa phân quyền user");
            return;
        }
        document.getElementById("EditForm").submit();
    }
</script>

dvhd/Views/users/Delete.cshtml
@model dvhd.Models.user

@{
    ViewBag.Title = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>user</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pass)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pass)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.groups)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.groups)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.permission)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.permission)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Trở về danh sách", "Index")
    </p>
}

dvhd/Views/users/Details.cshtml
@model dvhd.Models.user

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Details</h2>

<fieldset>
    <legend>user</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.name)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.name)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.pass)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.pass)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.groups)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.groups)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.permission)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.permission)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
    @Html.ActionLink("Trở về danh sách", "Index")
</p>

dvhd/Views/users/Edit.cshtml
@model dvhd.Models.user

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2>Cập nhật user và phân quyền</h2>
@using (Html.BeginForm("Edit", "users", FormMethod.Post, new { id = "EditForm" })) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(false)
    <fieldset>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">User name * </label>
                 <input name="name" type="text" tabindex="1" id="name" value="@Model.name" disabled class="form-control" placeholder="Nhập user name"/>               
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">password * </label>
                 <input name="pass" type="password" tabindex="1" id="pass" value="" class="form-control" placeholder="Nhập password"/>               
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                  <input type="button" value="Đổi mật khẩu" onclick="checkField();"/>
              </div>
        </div>      
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">Thuộc đơn vị * </label>
                 <select id="groups" class="form-control" name="groups" tabindex="33" onchange="changePermission();">                   
                    <option value="Tổng cục môi trường">Tổng cục môi trường</option>
                    <option value="Cảnh sát môi trường" selected>Cảnh sát môi trường</option>
                    <option value="Hải quan">Hải quan</option>
                    <option value="Kiểm lâm">Kiểm lâm</option>
                    <option value="Quản lý thị trường">Quản lý thị trường</option>
                    <option value="Viện kiểm sát">Viện kiểm sát</option>
                    <option value="Tòa án">Tòa án</option>
                    <option value="Cơ quan điều tra">Cơ quan điều tra</option>
                    <option value="Nhập dữ liệu">Nhập dữ liệu</option>
                    <option value="Admin hệ thống">Admin hệ thống</option>
                </select>              
                <script>document.getElementById("groups").value="@Html.Raw(@Model.groups)";</script>
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">PHÂN QUYỀN CHO USER</label>
                 <input type="checkbox" id="ALL" onclick="checkAll(this, 'ALL');">TẤT CẢ   
                 <input type="hidden" value="@Model.permission" id="permission" name="permission">          
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="HS" onclick="checkHS();">Quyền truy cập Quản lý hồ sơ vi phạm</label>
                 <input type="checkbox" id="HS0" onclick="checkPermission(this, 'HS0');">Xem danh sách 
                 <input type="checkbox" id="HS1" onclick="checkPermission(this, 'HS1');">Tạo mới hồ sơ
                 <input type="checkbox" id="HS2" onclick="checkPermission(this, 'HS2');">Xem và in hồ sơ 
                 <input type="checkbox" id="HS3" onclick="checkPermission(this, 'HS3');">Sửa hồ sơ 
                 <input type="checkbox" id="HS4" onclick="checkPermission(this, 'HS4');">Xóa hồ sơ             
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="BC_1_5" onclick="checkBC(1, 5);">Quyền truy cập Tra cứu hồ sơ</label>
                 <input type="checkbox" id="BC1" onclick="checkPermission(this, 'BC1');">Tra cứu theo loài bị vi phạm
                 <input type="checkbox" id="BC2" onclick="checkPermission(this, 'BC2');">Tra cứu theo địa bàn vi phạm
                 <input type="checkbox" id="BC3" onclick="checkPermission(this, 'BC3');">Tra cứu theo đối tượng vi phạm
                 <input type="checkbox" id="BC4" onclick="checkPermission(this, 'BC4');">Tra cứu theo đơn vị bắt giữ
                 <input type="checkbox" id="BC5" onclick="checkPermission(this, 'BC5');">Tra cứu theo đơn vị xử lý
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="BC_6_11" onclick="checkBC(6, 11);">Quyền truy cập xem các báo cáo</label>
                 <input type="checkbox" id="BC6" onclick="checkPermission(this, 'BC6');">Xem báo cáo theo hình thức vi phạm(hành chính, hình sự)
                 <input type="checkbox" id="BC7" onclick="checkPermission(this, 'BC7');">Xem báo cáo theo hành vi vi phạm(buôn bán, vận chuyển, nuôi nhốt...)
                 <input type="checkbox" id="BC8" onclick="checkPermission(this, 'BC8');">Xem báo cáo số vụ xử lý hành chính
                 <input type="checkbox" id="BC9" onclick="checkPermission(this, 'BC9');">Xem báo cáo số vụ xử lý hình sự
                 <input type="checkbox" id="BC10" onclick="checkPermission(this, 'BC10');">Xem báo cáo số vụ không xử lý 
                 <input type="checkbox" id="BC11" onclick="checkPermission(this, 'BC11');">Xem báo cáo tổng hợp   
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;"><input type="checkbox" id="US" onclick="checkUS();">Quyền truy cập quản lý user đăng nhập</label>
                 <input type="checkbox" id="US0" onclick="checkPermission(this, 'US0');">Xem danh sách user đăng nhập
                 <input type="checkbox" id="US1" onclick="checkPermission(this, 'US1');">Tạo user đăng nhập
                 <input type="checkbox" id="US2" onclick="checkPermission(this, 'US2');">Sửa user đăng nhập 
                 <input type="checkbox" id="US3" onclick="checkPermission(this, 'US3');">Xóa user đăng nhập    
              </div>
        </div>
        <div class="col-md-12">
          <div class="form-group">
            <input type="button" value="Cập nhật quyền" onclick="updatePermission();"/>
          </div>
        </div>
    </fieldset>
}    
<div>
    @Html.ActionLink("Trở về danh sách", "Index")
</div>
<script>
    function showPermission(permission) {
        var count = 0;
        var totalcount = 0;
        for (var i = 0; i <= 4; i++)
            if (permission.indexOf("HS"+i+",")>=0)
            {
                totalcount++;
                count++;
                document.getElementById("HS" + i).checked = true;
            }
        if (count >= 5) document.getElementById("HS").checked = true;
        count = 0;
        for (var i = 1; i <= 5; i++)
            if (permission.indexOf("BC" + i+",") >= 0) {
                totalcount++;
                count++;
                document.getElementById("BC" + i).checked = true;
            }
        if (count >= 5) document.getElementById("BC_1_5").checked = true;
        count = 0;
        for (var i = 6; i <=11; i++)
            if (permission.indexOf("BC" + i+",") >= 0) {
                totalcount++;
                count++;
                document.getElementById("BC" + i).checked = true;
            }
        if (count >= 6) document.getElementById("BC_6_11").checked = true;
        count = 0;
        for (var i = 0; i <= 3; i++)
            if (permission.indexOf("US" + i+",") >= 0) {
                totalcount++;
                count++;
                document.getElementById("US" + i).checked = true;
            }
        if (count >= 4) document.getElementById("US").checked = true;
        if (totalcount >= 20) document.getElementById("ALL").checked = true;

    }
    showPermission("@Model.permission");
    function checkField() {
        //alert(document.getElementById("permission").value);
        //return;
        if (document.getElementById("name").value == "") {
            alert("Nhập user name");
            document.getElementById("name").focus();
            return;
        }
        if (document.getElementById("pass").value == "") {
            alert("Nhập password");
            document.getElementById("pass").focus();
            return;
        }
        if (document.getElementById("permission").value == "") {
            alert("Bạn chưa phân quyền user");
            return;
        }
        document.getElementById("EditForm").submit();
    }
    function updatePermission() {
        if (document.getElementById("permission").value == "") {
            alert("Bạn chưa phân quyền user");
            return;
        }
        //alert(document.getElementById("permission").value);
        //return;
        var id = @ViewBag.id;
        var permission=document.getElementById("permission").value;
        var formdata = new FormData(); //FormData object
        formdata.append("id", id);
        formdata.append("permission", permission);
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/users/updatePermission');
        xhr.send(formdata);
        var content = "";
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                if (xhr.responseText == 0) {
                    alert("Lỗi không cập nhật được phân quyền, kiểm tra hệ thống!");
                } else {
                    alert("Cập nhật quyền cho user thành công!");
                    window.location.href = "/users/Index";
                }
            }
        }
    }
</script>

dvhd/Views/users/Index.cshtml
@model PagedList.IPagedList<dvhd.Models.user>
@using PagedList.Mvc; 
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style id="styleDetail" type="text/css">
   /* Ban In css*/
    .tbBanIn {
        width:100%;
        border: 1px solid #bbbcbb;
        border-collapse: collapse;
    }
    .tbBanIn td, .tbBanIn th {
        border: 1px solid #bbbcbb;
        padding: 2px !important;
    }
    .tbBanIn label {
        margin: 0 !important;
    }
</style>
<h2>Danh sách user quản trị</h2>
<p>
    @Html.ActionLink("Thêm mới", "Create")
</p>

<table class="tbBanIn">
    <tr>
        <th>
            Tên user
        </th>
        <th>
            Đơn vị
        </th>  
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @item.name
        </td>
        <td width="20%">
            @item.groups
        </td>
        <td>
            @Html.ActionLink("Sửa", "Edit", new { id=item.id }) |
            @Html.ActionLink("Xóa", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>
@if (Model.PageCount>1){
    <div class="col-md-12">
    <ul class="pagination clearfix">
            <li class="disabled"><a href="#">«</a></li>
            @for (int i = 1; i <= Model.PageCount; i++)
            {
                if (i != ViewBag.page){
                   <text><li><a href="/hoso/Index?page=@i">@i</a></li></text>
                }else{
                   <text><li><a href="/hoso/Index?page=@i" style="background-color:#ddd ;">@i</a></li></text>
                }
            }
    </ul>
    </div>
}

dvhd/Views/users/changePass.cshtml
@{
    ViewBag.Title = "changePass";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2 style="margin-left:10px;">Đổi mật khẩu</h2>

    <fieldset>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">Mật khẩu cũ * </label>
                 <input name="oldpass" type="password" tabindex="1" id="oldpass" value="" class="form-control" placeholder="Nhập password"/>                  
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                 <label for="room" style="width:auto;display:block;">Mật khẩu mới * </label>
                 <input name="pass" type="password" tabindex="2" id="pass" value="" class="form-control" placeholder="Nhập password"/>
                 <label for="room" style="width:auto;display:block;">Nhập lại mật khẩu mới * </label>
                 <input name="pass2" type="password" tabindex="2" id="pass2" value="" class="form-control" placeholder="Nhập password"/>                               
              </div>
        </div>
        <div class="col-md-12">
              <div class="form-group">
                  <input type="button" value="Đổi mật khẩu" onclick="checkField();"/>
              </div>
        </div>      
        
    </fieldset>
   
<script>
    
    function checkField() {
        //alert(document.getElementById("permission").value);
        //return;
        if (document.getElementById("oldpass").value == "") {
            alert("Nhập mật khẩu cũ");
            document.getElementById("oldpass").focus();
            return;
        }
        if (document.getElementById("pass").value == "") {
            alert("Nhập mật khẩu mới");
            document.getElementById("pass").focus();
            return;
        }
        if (document.getElementById("pass2").value == "") {
            alert("Nhập lại mật khẩu mới");
            document.getElementById("pass2").focus();
            return;
        }
        if (document.getElementById("pass").value != document.getElementById("pass2").value) {
            alert("Nhập lại mật khẩu mới phải giống nhau");
            document.getElementById("pass2").focus();
            return;
        }
        var formdata = new FormData(); //FormData object
        var oldpass = document.getElementById("oldpass").value;
        var pass = document.getElementById("pass").value;        
        formdata.append("id", @ViewBag.id);
        formdata.append("oldpass", oldpass);
        formdata.append("pass", pass);        
        var xhr = new XMLHttpRequest();
        xhr.open('POST', '/users/updatePass');
        xhr.send(formdata);
        var content = "";
        xhr.onreadystatechange = function () {
            if (xhr.readyState == 4 && xhr.status == 200) {
                if (xhr.responseText == 0) {
                    alert("Sai mật khẩu cũ!");
                } else {
                    alert("Cập nhật thành công!");
                    window.location.href = "/Home/Index";
                }
            }
        }
    }
    
</script>